//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyVanity.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin : User 
    {
        public Admin()
        {
            this.Reports = new HashSet<Report>();
        }
    
    
        public virtual ICollection<Report> Reports { get; set; }
    }
}
