//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyVanity.Domain
{
    using System;
    
    public enum AgentType : int
    {
        SurgicalCoordinator = 0,
        FinanceCoordinator = 1,
        MedicalAssistant = 2,
        HomeAwayAssistant = 3
    }
}
