//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyVanity.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment : IEntity 
    {
        public int Id { get; set; }
        public int UserProcedureId { get; set; }
        public System.DateTime Date { get; set; }
        public AppointmentStatus Status { get; set; }
        public string Description { get; set; }
        public int PlaceId { get; set; }
    
        public virtual UserProcedure Procedure { get; set; }
        public virtual Place Place { get; set; }
    }
}
