//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyVanity.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConsentForm : IEntity 
    {
        public ConsentForm()
        {
            this.UserProcedureConsentSigns = new HashSet<UserProcedureConsentSign>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string FilePath { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<UserProcedureConsentSign> UserProcedureConsentSigns { get; set; }
    }
}
