//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyVanity.Domain
{
    using System;
    
    public partial class Contact
    {
        public Contact()
        {
            this.Phone = new Phone();
            this.Social = new Social();
        }
    
        public string Address { get; set; }
        public string Address1 { get; set; }
        public string ZipCode { get; set; }
    
        public Phone Phone { get; set; }
        public Social Social { get; set; }
    }
}
