//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyVanity.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient : User 
    {
        public Patient()
        {
            this.Procedures = new HashSet<UserProcedure>();
            this.Documents = new HashSet<PatientDocument>();
            this.UserProcedurePatientDocuments = new HashSet<UserProcedurePatientDocument>();
            this.Profile = new PersonDetails();
            this.Contact = new Contact();
        }
    
        public int AgentId { get; set; }
        public string Email { get; set; }
        public string PicPath { get; set; }
        public string PatientNumber { get; set; }
    
        public PersonDetails Profile { get; set; }
        public Contact Contact { get; set; }
    
        public virtual ICollection<UserProcedure> Procedures { get; set; }
        public virtual ICollection<PatientDocument> Documents { get; set; }
        public virtual Agent Agent { get; set; }
        public virtual ICollection<UserProcedurePatientDocument> UserProcedurePatientDocuments { get; set; }
    }
}
