//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyVanity.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Place : IEntity 
    {
        public Place()
        {
            this.UserProcedures = new HashSet<UserProcedure>();
            this.Appointments = new HashSet<Appointment>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<UserProcedure> UserProcedures { get; set; }
        public virtual ICollection<Appointment> Appointments { get; set; }
    }
}
