//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyVanity.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProcedurePatientDocument : Document 
    {
        public int UserProcedureId { get; set; }
        public int PatientId { get; set; }
    
        public virtual UserProcedure UserProcedure { get; set; }
        public virtual Patient Patient { get; set; }
    }
}
