//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyVanity.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProcedure : IEntity 
    {
        public UserProcedure()
        {
            this.Appointments = new HashSet<Appointment>();
            this.Doctors = new HashSet<Doctor>();
            this.Agents = new HashSet<Agent>();
            this.SharedDocuments = new HashSet<SharedDocument>();
            this.UserProcedurePatientDocuments = new HashSet<UserProcedurePatientDocument>();
            this.UserProcedureConsentSigns = new HashSet<UserProcedureConsentSign>();
        }
    
        public int Id { get; set; }
        public int PatientId { get; set; }
        public int ProcedureId { get; set; }
        public int PlaceId { get; set; }
    
        public virtual Patient Patient { get; set; }
        public virtual Procedure Procedure { get; set; }
        public virtual ICollection<Appointment> Appointments { get; set; }
        public virtual ICollection<Doctor> Doctors { get; set; }
        public virtual ICollection<Agent> Agents { get; set; }
        public virtual ICollection<SharedDocument> SharedDocuments { get; set; }
        public virtual ICollection<UserProcedurePatientDocument> UserProcedurePatientDocuments { get; set; }
        public virtual ICollection<UserProcedureConsentSign> UserProcedureConsentSigns { get; set; }
        public virtual Place Place { get; set; }
    }
}
